import Head from "next/head";
import Header from "./Header";
import StickyCursor from "./StickyCursor";
import { useRef } from "react";

function Page({ children }) {
  const stickyElement = useRef();
  return (
    <div>
      <Head>
        <title>Madhan Kumar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header ref={stickyElement} />
      <StickyCursor stickyElement={stickyElement} />
      {children}
    </div>
  );
}

export default Page;
